// examples/expo/src/ElectricProvider.tsx
import React, { useEffect, useState } from 'react'
import { authToken } from './auth'
import { DEBUG_MODE, ELECTRIC_URL } from './config'
import { Electric, schema } from './generated/client'

import * as SQLite from 'expo-sqlite/next'

import { electrify } from '@anta-semenov/electric-sql/expo-next'
import { makeElectricContext } from '@anta-semenov/electric-sql/react'

const { ElectricProvider, useElectric } = makeElectricContext<Electric>()

const ElectricProviderComponent = ({
  children,
}: {
  children: React.ReactNode
}) => {
  const [electric, setElectric] = useState<Electric>()

  useEffect(() => {
    let isMounted = true

    const init = async () => {
      const config = {
        debug: DEBUG_MODE,
        url: ELECTRIC_URL,
      }

      const conn = SQLite.openDatabaseSync('electric.db')
      const client = await electrify(conn, schema, config)
      await client.connect(authToken())

      if (!isMounted) {
        return
      }

      setElectric(client)
    }

    init()

    return () => {
      isMounted = false
    }
  }, [])

  if (electric === undefined) {
    return null
  }

  return <ElectricProvider db={electric}>{children}</ElectricProvider>
}

export { ElectricProviderComponent as ElectricProvider, useElectric }

// examples/web-wa-sqlite-vuejs/src/ElectricProvider.vue
<script lang="ts" setup>
import { onMounted, shallowRef } from 'vue'
import { LIB_VERSION } from '@anta-semenov/electric-sql/version'
import { uniqueTabId } from '@anta-semenov/electric-sql/util'
import { ElectricDatabase, electrify } from '@anta-semenov/electric-sql/wa-sqlite'
import { authToken } from './auth'
import { provideElectric } from './electric'
import { Electric, schema } from './generated/client'

const electric = shallowRef<Electric>()

onMounted(async () => {
  const config = {
    debug: import.meta.env.DEV,
    url: import.meta.env.ELECTRIC_SERVICE,
  }

  const { tabId } = uniqueTabId()
  const scopedDbName = `basic-${LIB_VERSION}-${tabId}.db`

  const conn = await ElectricDatabase.init(scopedDbName)
  const client = await electrify(conn, schema, config)
  await client.connect(authToken())


  // Resolves when the shape subscription has been established.
  const shape = await client.db.items.sync()

  // Resolves when the initial data for the shape
  // has been synced into the local database.
  await shape.synced

  electric.value = client
})

provideElectric(electric)
</script>

<template>
  <div v-if="electric">
    <slot />
  </div>
</template>
